name: "🐛 Bug Report"
description: Report unexpected behavior or errors
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "What's broken? What did you expect?"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "e.g. GitHub Actions, Jamf Pro 11.x"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Trigger webhook\n2. Observe error message..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Output
      placeholder: "Paste relevant logs or output (redact sensitive info)"
    validations:
      required: false
