name: "\U0001F4A1 Feature Request"
description: Suggest an enhancement or improvement
title: "[Feature Request] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Brief one-line summary of the feature you're requesting
      placeholder: e.g. "Add support for Slack notifications on successful redeploy"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: Describe your problem or context...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What would you like to see happen?
      placeholder: e.g. "Add a Slack webhook step to the GitHub Action..."
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Scope of Impact
      description: What areas of the project does this affect?
      options:
        - label: GitHub Actions workflows
        - label: FastAPI webhook service
        - label: Jamf Pro setup
        - label: Documentation
        - label: Other
