name: Scheduled Jamf Framework Redeploy

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 2 * * 1'  # Runs every Sunday 7 PM PT (Monday 2 AM UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      JAMF_CLIENT_ID: ${{ secrets.JAMF_CLIENT_ID }}
      JAMF_CLIENT_SECRET: ${{ secrets.JAMF_CLIENT_SECRET }}
      JAMF_BASE_URL: ${{ secrets.JAMF_BASE_URL }}
      GROUP_ID: ${{ secrets.GROUP_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install SDK
        run: pip install -e ./jamf-pro-sdk

      - name: Run main script
        id: main-script
        run: |
          set -o pipefail
          python3 scripts/main.py | tee main_output.txt
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          cat main_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            *Scheduled redeploy run result:* ${{ job.status }}
            *Script output:*
            ```
            ${{ steps.main-script.outputs.script_output }}
            ```
